= OpenSMTPD filter-rewrite-from
:script-name: filter-rewrite-from.awk

This is a _very_ simple OpenSMTPD filter that either:

. rewrites the email address in the `From` and `Reply-To` headers with a
  specified domain where rcpt-to does not contain <domain> (i.e a
  masquerade for external destinations), or

. rewrites the email address in both `MAIL FROM` command and the `From` and
 `Reply-To` headers in all messages with a specified email address.
  It’s useful when you want to ensure that all the relayed messages will
  be “sent from” some _no-reply_ email address.

== Requirements

* http://pubs.opengroup.org/onlinepubs/009695399/utilities/awk.html[POSIX awk] (e.g. from Busybox, GNU, BSD, …)
* https://www.opensmtpd.org/[OpenSMTPD] 6.6.0 or higher


== Installation

Just copy link:{script-name}[{script-name}] to some directory,
e.g. `/usr/local/share/opensmtpd`.

== Configuration

The filter itself requires no configuration, but must be supplied with
two arguments: either "masquerade <domain>" or "address <mailaddr>".

It must be declared in smtpd.conf and attached to a listener:

[source, subs="+attributes"]
----
filter "rewrite-from" proc-exec "/path/to/script address no-reply@example.org"

listen on socket filter "rewrite-from"
----


== See Also

* https://man.openbsd.org/smtpd.conf
* https://man.openbsd.org/smtpd-filters

== License

This project is licensed under http://opensource.org/licenses/ISC/[ISC License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
